CREATE DATABASE IF NOT EXISTS hackatondb;
USE hackatondb;

CREATE TABLE IF NOT EXISTS Video (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CaminhoArquivo VARCHAR(255) NOT NULL,
    NomeArquivo VARCHAR(100) NOT NULL,
    Intervalo INT NOT NULL,
    DtCriacao DATETIME DEFAULT CURRENT_TIMESTAMP,
    Zip VARCHAR(500) NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Imagem (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    IdVideo INT NOT NULL,
    CaminhoArquivo VARCHAR(255) NOT NULL,
    NomeArquivo VARCHAR(100) NOT NULL,
    DtCriacao DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Imagem_Video FOREIGN KEY (IdVideo) REFERENCES Video(Id)
) ENGINE=InnoDB;
